### PR TITLE
Expose `kall` to user ASM

### PR DESCRIPTION
**Pull request by ben-chain**
### Description
This allows us to put `kall` directly into inline yul, by making the `kall` builtin use imaginary opcodes which don't get transpiled.  (Still gets find-replaced at the end, of course!)

### CODE REVIEW

**Comment by snario** [comment]
Is there documentation somewhere on what `kall` is?

**Review by smartcontracts — APPROVED** [review]

**Comment by smartcontracts** [comment]
Ben explained the trick to me and it works. I think it would be worth explaining this in more detail in comments within the code though.

**Comment by ben-chain** [comment]
Update: I am not gonna merge this one until we've used the `soljson.js` file in local testing with the `contracts`.  This has been published [here](https://github.com/ethereum-optimism/solc-bin/commit/dae0b80f311f674fbe496f3008347f7656fa768c) in a way that we can use a custom version before updating the main json!

**Comment by snario** [comment]
Can I propose that we come up with a different name than `kall`? Maybe `em_call`? It seems like `kall` is just a modification of `call` with a letter making the opcode name sound like the word "call", but it doesn't really say much about what this function is actually doing. This may be out of scope for this pull request.

**Comment by ben-chain** [comment]
@snario I want to merge this PR now that it's confirmed working but agree naming could be improved.  Maybe Yul IR compiler is the right time to make the switch.

**Pull request merged**
